[package]
name = "anlaut-4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
ecs = { git = "https://github.com/geng-engine/ecs", rev = "203158db73b2e2d2bdd0b491d7097c70b54f1ea6" }
geng = { git = "https://github.com/kuviman/geng", rev = "37d3a3040f39d170b1e6cce854de4e9288ec9bd2" }
parry2d = "0.13.4"
serde = { version = "1.0.164", features = ["derive"] }
