background = "#1b1b1b"
gasoline = "#edab50"

health_fg = "#c42430"
health_bg = "#0e071b"

outline_color = "#0e071b"

# UNUSED ???
fire = "#c42430"
fire_particles = "#c42430"
player = "#009FB7"
projectile = "#9FFFCB"

[enemies] # UNUSED ???
crawler = "#6D545D"
ranger = "#6D545D"

[pickups]
heal = "#99e65f"

[palette]
fg_blue = "#0069aa"
fg_red = "#7c2d2b"
fg_green = "#33984b"

bg_gray = "#272727"
bg_light_gray = "#3d3d3d"

[level]
foreground = ["fg_blue", "fg_red", "fg_green"]
background = ["bg_gray", "bg_gray", "bg_light_gray"]
