background = "#232221"
player = "#009FB7"
projectile = "#9FFFCB"
gasoline = "#f1be43"
fire = "#cb2f2c"
fire_particles = "#ff5502"
health_bg = "#0008"
health_fg = "#F308"

[enemies]
crawler = "#6D545D"
ranger = "#6D545D"
